import smtplib
from email.message import EmailMessage

def send_email(sender_email, sender_password, recipients, subject, description, smtp_server="smtp.gmail.com", smtp_port=587):
    try:
        msg = EmailMessage()
        msg["From"] = sender_email
        msg["To"] = ", ".join(recipients)
        msg["Subject"] = subject

        # محتوى HTML بدل set_content
        msg.add_alternative(description, subtype="html")

        with smtplib.SMTP(smtp_server, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            server.send_message(msg)
            print("✅ Email sent successfully!")
    except Exception as e:
        print(f"❌ Error: {e}")


if __name__ == "__main__":
    sender_email = "vendoroperations@raneen.io"       
    sender_password = "vumo kmkq syee bymd" 

    recipients = [
        "muhammad.ramadan91996@gmail.com","ramadan.abbas@raneen.com","Abdelrahman.amr@raneen.com",
        "shoukryattallah@gmail.com",
        "tradingo.raneen@gmail.com",
        "zayed.aac@gmail.com",
        "eslam.m.yousef15@gmail.com",
        "raneenmazloum@gmail.com",
        "karemnossier@gmail.com",
        "katoshhamed3@gmail.com",
        "rofaeel3011@gmail.com",
        "a.shazly1969@yahoo.com",
        "homran@iq.mobiles.com",
        "artcool1010@gmail.com",
        "aquatec2005@gmail.com",
        "hhsn73465@gmail.com",
        "aymanelsoudy1@gmail.com",
        "salemelectric1992@gmail.com",
        "groovyinteriors9@gmail.com",
        "masnaahram@gmail.com",
        "elmanar.ranin@gmail.com",
        "arcomairnew@gmail.com",
        "omartharwatmohamed@gmail.com",
        "sellerstore2020@yahoo.com",
        "Alzyyms@GMAIL.COM",
        "furniturefuture1@gmail.com",
        "raneen@radiotalaat.com",
        "mhossam11@yahoo.com",
        "home.technology2024@gmail.com",
        "dukanegroup@gmail.com",
        "e-commerce@mobileplus-egypt.com",
        "woodrate2020@gmail.com",
        "wowmartegypt@gmail.com",
        "whiteair80@gmail.com",
        "ztrueline@gmail.com",
        "Ganacool.1414@gmail.com",
        "hany.yehya.mtech@gmail.com",
        "newaircompany2022@gmail.com",
        "athomefurniture45@gmail.com",
        "mahmedahmedmam321@gmail.com",
        "wooddeenn@gmail.com",
        "mohamedelogeil72@gmail.com",
        "i.ossama@2b.com.eg",
        "goldsmart1000@gmail.com",
        "asia.one.eg@gmail.com",
        "momoglal28@gmail.com",
        "sales@shahpor.com",
        "handsiagroup@gmail.com",
        "ahassan2015@gmail.com",
        "mallelsaad@gmail.com",
        "top.tech2022@yahoo.com",
        "rbyabwhsn488@gmail.com",
        "online@electronichouse.org",
        "zomamodern@gmail.com",
        "online@arabcomputer.net",
        "smartdirection315@gmail.com",
        "melsoobky@gmail.com",
        "starco@carrieregypt-dealers.com",
        "global.m.home.tech@gmail.com",
        "ahmed.ezz21983@gmail.com",
        "linesleep.eg@gmail.com",
        "ahmedkhaled885544@gmail.com",
        "ahmedaid13101984@gmail.com",
        "dukan3laaeldin@gmail.com",
        "smart.future1189@gmail.com",
        "abdelazizstreet.co@gmail.com",
        "magdy.hassan267@gmail.com",
        "capitaltech23@gmail.com",
        "elreada43@gmail.com",
        "mzakaria.elkabeer@gmail.com",
        "tahawy700@gmail.com",
        "Raneen@egyptlaptop.com",
        "marwanhossam98@gmail.com",
        "nourelmanzlawy@yahoo.com",
        "brideshousedm@gmail.com",
        "ma.salah@elite-tradeeg.com",
        "malaaztrade@gmail.com",
        "ops@furvive.com",
        "alzohury45@gmail.com",
        "kareemnaem41@gmail.com",
        "prime.store098@gmail.com",
        "prestigemattress9@gmail.com",
        "mohamedfarouk7877@gmail.com",
        "tamerwaheed00@gmail.com",
        "a.m.k.mal57@gmail.com",
        "diaa_dh2000@yahoo.com",
        "more.tech84@gmail.com",
        "Elgebalytex@yahoo.com",
        "aldora.online@aldora-egypt.com",
        "info@lazord-cookware.com",
        "nas033310@gmail.com",
        "mohamedelattal049@gmail.com",
        "abdelmalaksamir2018@gmail.com",
        "mohabyossry12@gmail.com",
        "ibrahimlotfy9999@gmail.com",
        "m7med99224@gmail.com",
        "ridamahmoud1971@gmail.com",
        "michaelatef7770@gmail.com",
        "magfurnitureeg@gmail.com",
        "sabdomohamed151@gmail.com",
        "newsmartfuture@gmail.com",
        "catchoo.83@gmail.com",
        "ahmed.sabry1004@gmail.com",
        "steel.251180@gmail.com",
        "info@purity-101.com",
        "sayedabdellahsayed@gmail.com",
        "adham.mohamed@dubaiphone.net",
        "selectionhomewear@gmail.com",
        "ahmedalassy8@gmail.com",
        "dinasfarid@hotmail.com",
        "allinoneemam@gmail.com",
        "eggyypptt2022@gmail.com",
        "ahmdalfrmawy050@gmail.com",
        "ezzatmohamed867@gmail.com",
        "pr@mts-egypt.com",
        "mt74ua07@gmail.com",
        "goldeneagle.group2@gmail.com",
        "aeroegy@gmail.com",
        "lap.tech.egypte@gmail.com",
        "balcagamat@gmail.com",
        "ansmgamal@gmail.com",
        "newv0012@gmail.com",
        "akaeegypt@gmail.com",
        "hessenradwan75@gmail.com",
        "karamelamostafa@gmail.com",
        "mohamed.badr@testatoro.com",
        "vipmarketing654@gmail.com",
        "ayman.yousry@etc-egy.net",
        "E-commerce@tiba-snooze.com",
        "omaras.ylights@gmail.com",
        "mahwash041@gmail.com",
        "mostafa.ahmed@tredcoelsayad.com",
        "stargetshop1@gmail.com",
        "e01501551350@gmail.com",
        "roayastore2021@gmail.com",
        "mixat.company@gmail.com",
        "Hanadyfouad@gmail.com",
        "Soft.death84@gmail.com",
        "superpharma98@gmail.com",
        "elbana@rivalgroup-eg.com",
        "marketingteam@penguin-appliances.com",
        "mo4koko@gmail.com",
        "bedn1home@gmail.com",
        "lionhomeeg@gmail.com",
        "wamr25936@gmail.com",
        "sarahsameh272@gmail.com",
        "abdotalha188@gmail.com",
        "syd912468@gmail.com",
        "ahmed.elnahrawy@bshg.com",
        "afarouk@thebesint.com",
        "shoppingnour27@gmail.com",
        "salehselem2017@gmail.com",
        "nesma@wb.com.eg",
        "mahmeudsaid4@gmail.com",
        "yasmin.yousry@maccarpet.com",
        "ali.adawex5@gmail.com",
        "mrawansabry30@gmail.com",
        "seenewdeals@gmail.com",
        "abozied2083@gmail.com",
        "3w.elbasha@gmail.com",
        "antikasteel@gmail.com",
        "elmotahida.co@gmail.com",
        "kkandil764@gmail.com",
        "hmousa@cairotrading.com",
        "somyoblue@gmail.com",
        "signoola@gmail.com",
        "wonders.92@yahoo.com",
        "asyasy375@gmail.com",
        "khattabkh3@gmail.com",
        "magicocamera@gmail.com",
        "ahmedsamy007765@gmail.com",
        "elbassantfurniture@gmail.com",
        "omarmorad01154395140@gmail.com",
        "m.eldesouky@elnilegroup.com",
        "yousefeslam866@gmail.com",
        "fantastickidstoys2021@gmail.com",
        "elslamony074@gmail.com",
        "samrahomesmsm@gmail.com",
        "sydaldktwr61@gmail.com",
        "bedobusiness2221@gmail.com",
        "zahran88999@gmail.com",
        "etielmasria@gmail.com",
        "imzone.onlineservies@gmail.com",
        "fabric.desg@gmail.com",
        "safktna@gmail.com",
        "Esraaelmsry16@gmail.com",
        "elghonemyhazem@gmail.com",
        "marketing@ammam-group.com",
        "Info@aeromea.com",
        "Anas.zaki@mfaelectronics.com",
        "motaz@arab-security.com",
        "Souqmasr2023@gmail.com",
        "ahmedmoussaaa76@gmail.com",
        "armwood4art@gmail.com",
        "mohamed.amazon12345@gmail.com",
        "ibrahim.farag1991@gmail.com",
        "ezz@homeproeg.com",
        "Alrawystore116@gmail.com",
        "ziadkhattab082@gmail.com",
        "acc.mohamed5858@gmail.com",
        "souqstore72@gmail.com",
        "sohirelshref5555@gmail.com",
        "eslameslamza09324@gmail.com",
        "haithamyoussef89@gmail.com",
        "mahmoudshahrzd@gmail.com",
        "woodwaycompany2@gmail.com",
        "e01279696311@gmail.com",
        "airkarly@gmail.com",
        "solutionsxall@gmail.com",
        "eng.mahmoudaatef@gmail.com",
        "nasserahmed1173@gmail.com",
        "Highsleep.raneen@gmail.com",
        "Info@baityegy.com",
        "nagfa.shop@gmail.com",
        "bahgatmahmoudsamy@gmail.com",
        "comotory17@gmail.com",
        "elelnaser@gmail.com",
        "makagroup806@gmail.com",
        "justingeorgemansour@gmail.com",
        "domanigroupeg@gmail.com",
        "ecommerce@arpinatech.com",
        "nsama3243@gmail.com",
        "zeyad@sunny.com",
        "takeef.com2023@gmail.com",
        "modemedo327@gmail.com",
        "m.s.baset2014@gmail.com",
        "mwzykaa@gmail.com",
        "a.store.eg@hotmail.com",
        "aufgroup24@gmail.com",
        "shoppingnoon.91@gmail.com",
        "info@kaian-trading.com",
        "Mahmoud.alii5560@gmail.com",
        "safwa.skills@gmail.com",
        "Besho_tefa@yahoo.com",
        "tamer.safwat.ts@gmail.com",
        "alaqmardesign@gmail.com",
        "printovasales@gmail.com",
        "sales.ikdesigns@gmail.com",
        "AgStore.Raneen@gmail.com",
        "marketplace@grdtrading.com",
        "sherifreda6969@gmail.com",
        "khaled.fekra1@gmail.com",
        "alwaleed.import.nozha@gmail.com",
        "ayaelriada@gmail.com",
        "bean2go.eg@gmail.com",
        "abdoneuer3@gmail.com",
        "mohamed.tareq1994@gmail.com",
        "engkhaled5053@yahoo.com",
        "na8581sale@gmail.com",
        "Whegab3@gmail.com",
        "DRAHMEDFAWZY242@GMAIL.COM",
        "elegnthome067@gmail.com",
        "saver_mendleev@yahoo.com",
        "muh.abdallah07@gmail.com",
        "furniture.store1991@gmail.com",
        "support@ekitchen.com.eg",
        "online@newalfamisr-eg.com",
        "yoyo2016n@gmail.com",
        "hagarmarvelklm@gmail.com",
        "khattabkh30@gmail.com",
        "alrhma2010@yahoo.com",
        "Zo8la1996@icloud.com",
        "sales@penguin-eg.com",
        "m.fathy@eastrentechnology.com",
        "pavoneegy@gmail.com",
        "Cartelafabrics@gmail.com",
        "hossam.amen20@gmail.com",
        "wessamwaheb@gmail.com",
        "caesarbrand1@gmail.com",
        "Khaledmetwally88@gmail.com",
        "zezoelkady30@gmail.com",
        "ahmedsamyegy43@gmail.com",
        "Nancy@keendexegypt.com",
        "ahmedelpop485@gmail.com",
        "director@aura.egypt.com",
        "sales.jacquarddina@gmail.com",
        "aishafakre150@gmail.com",
        "vonhome11@gmail.com",
        "heshamkamal@arabtradeco.com",
        "ez.elgabry@hotmail.com",
        "egytechcompany@gmail.com",
        "30202015227@alexu.edu.eg",
        "atomsteel.eg@gmail.com",
        "mohamedelshorbagy734@gmail.com",
        "Moustafapharmacy72@gmail.com",
        "sales10@elhelow.com",
        "mostafa107794@gmail.com",
        "a.elwarraqy@gmail.com",
        "pointtradeonline@gmail.com",
        "specturmcomp2010@gmail.com",
        "Hadeeromara4@gmail.com",
        "madinaamonara@outlook.com",
        "amgadelprince79@gmail.com",
        "fatmaelgredly@icloud.com",
        "femtostores@gmail.com",
        "mahmoudonkel@gmail.com",
        "ahmed_genova@hotmail.it",
        "secondbike.eg@gmail.com",
        "sales.decorcenter@gmail.com",
        "nobletrade.eg@gmail.com",
        "b.e.s.decoration22@gmail.com",
        "sales.egy.pure@gmail.com",
        "mahmodelzogby@gmail.com",
        "mymsk2018@gmail.com",
        "mgomaa@sh.eg",
        "Ss4965473@gmail.com",
        "asfora.egy@gmail.com",
        "alisaqary48@gmail.com",
        "startranscommercial@gmail.com",
        "sales@trustofficeandhotel.com",
        "watches.raneen@hotmail.com",
        "mrabie@tigerslines.com",
        "kirolos.sorial27@gmail.com",
        "marketplace@gccegypt.com",
        "ssobhy@abouseif-group.com",
        "mayadamadeh1983@gmail.com",
        "alnourtechnology2020@gmail.com",
        "mahmoud_ahmed28324@yahoo.com",
        "mamdou7.nasr@gmail.com",
        "saadfuniture@gmail.com",
        "2mgroup012@gmail.com",
        "bestworker.1986@gmail.com",
        "mostafa@alahramcookware.com",
        "primegroup@primegroupp.com",
        "faridrizkalla2023@gmail.com",
        "weprintcontact2021@gmail.com",
        "sameh.nagah1@gmail.com",
        "glitterwomen.online@gmail.com",
        "elmatajer.for.trading@gmail.com",
        "MO_EBRAHEM@HOTMAIL.COM",
        "hany.elsherbiny13@gmail.com",
        "medhatbasta8@gmail.com",
        "alymorsyghm@gmail.com",
        "sherif.rashad@ufieg.com",
        "elrawdalighting@gmail.com",
        "amlomarfahmy@gmail.com",
        "esraahany598@gmail.com",
        "anjasportswear@gmail.com",
        "Info@artmood.co",
        "taghreedgamal211@gmail.com",
        "mrefatfanagely@gmail.com",
        "khalafawy23@hotmail.com",
        "info@skmeiegypt.com",
        "funnypot.56@gmail.com",
        "larumba.eg@gmail.com",
        "ehornets.eg@gmail.com"  
        ]

    subject = "استبيان أراء شركاء النجاح - رنين"
    description = """\
    <html>
    <body style="direction: rtl; text-align: right; font-family: Tahoma, Arial, sans-serif; font-size: 14px;">
        <p>السلام عليكم ورحمة الله وبركاته،</p>

        <p>شركاؤنا الأعزاء،<br>
        تحية طيبة من فريق رنين،</p>

        <p>
        إحنا بنقدّر جدًا تعاونكم ومجهودكم معانا، وبنعتبر رأيكم مهم جدًا لتطوير خدماتنا وتحسين تعاملنا معكم.<br>
        عشان كده عملنا استبيان سريع (ياخد من وقتكم دقيقة أو اثنتين)، هدفه نعرف إزاي نقدر نخدمكم بشكل أفضل، إيه اللي عاجبكم وإيه اللي ممكن نعدله.
        </p>

        <p>
        ياريت تشاركنا رأيك من خلال الفورم ده:<br>
        <a href="https://docs.google.com/forms/d/1h3IyyoVO5VaQcDqfMhUa1IVQOltSoc71nq08Ny6MsVE/viewform" target="_blank">
        اضغط هنا لفتح الاستبيان
        </a>
        </p>

        <p>
        ملاحظاتكم واقتراحاتكم هتساعدنا نوصل للأفضل دائمًا، وهدفنا إن تعاملنا معاكم يبقى أسهل وأسرع وأفضل بأي طريقة ممكنة.
        </p>

        <p>
        شاكرين لكم وقتكم ومشاركتكم،<br>
        تحياتي،<br>
        فريق رنين
        </p>
    </body>
    </html>
    """

    send_email(sender_email, sender_password, recipients, subject, description)
